[world]
name = "hexed"
description = "hexed"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "hexedseed_1"

[world.socials]
x = "https://x.com/0xjinius"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/FemiOje/hexed"
telegram = "https://t.me/dojoengine"

[namespace]
default = "hexed"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x03e4767d0616f48781ea197029a6be8e7209afeb2c029689e1853b487b760076"
account_address = "0x04033264fbcf087ee31b5940908e53956aa718a16fa1e6a51df778be45502c55"
keystore_path = "./deployments/keystore.json"

[writers]
"hexed" = ["hexed-game_systems"]
