[world]
name = "Untitled"
description = "literally untitled"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "dojo_starter_3"

[world.socials]
x = "https://x.com/0xjinius"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/FemiOje/untitled"
telegram = "https://t.me/dojoengine"

[namespace]
default = "untitled"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x06d22efbeabffade78c62af20900bd10d3fcf903512c7ea4fd8cbf31f45802cf"
account_address = "0x04033264fbcf087ee31b5940908e53956aa718a16fa1e6a51df778be45502c55"
keystore_path = "./deployments/keystore.json"

[writers]
"untitled" = ["untitled-actions"]
