[package]
name = "untitled"
version = "1.8.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
build = "PROFILE=sepolia && sozo -P $PROFILE clean && sozo -P $PROFILE build --typescript"
copy-bindings = "cp -r ./bindings/typescript/* ../client/src/typescript/"
deploy = "PROFILE=sepolia && sozo -P $PROFILE migrate && cp ./manifest_sepolia.json ../client/src/manifests/manifest_sepolia.json"
inspect = "PROFILE=sepolia && sozo -P $PROFILE inspect"

# build + copy bindings + deploy + inspect
migrate = "scarb run build && scarb run copy-bindings && scarb run deploy && scarb run inspect"

# example calls
spawn = "PROFILE=sepolia && sozo -P $PROFILE execute untitled-actions spawn --wait"
move = "PROFILE=sepolia && sozo -P $PROFILE execute untitled-actions move 1 --wait"

[dependencies]
dojo = "1.8.0"
starknet = "2.13.1"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.13.1"
dojo_cairo_test = "1.8.0"

[profile.sepolia]
