rpc = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x0014f000a33d9d3aad730ceb696842920aa2c5bf7fb13420b5522e0bc11f02d5"

[indexing]
contracts = [
  "erc20:0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH fee token
  "erc20:0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK fee token
]

[sql]
historical = [
  "untitled-Moves", 
  "untitled-DirectionsAvailable", 
  "untitled-Position", 
  "untitled-PositionCount",
  "untitled-Moved", 
  "untitled-Spawned", 
]

