rpc = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x01a8c69d89cd1833654f5061099256db624348e0dafa13dc5505924bab656f8a"

[indexing]
contracts = [
  "erc20:0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH fee token
  "erc20:0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK fee token
]

[sql]
historical = [
  "hexed-Moves", 
  "hexed-DirectionsAvailable", 
  "hexed-Position", 
  "hexed-PositionCount",
  "hexed-Moved", 
  "hexed-Spawned", 
]

