# rpc = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/BjyQOCq-LbYdwm4__atrb"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x05894380a511044d8546d34a4158a323fc135fbbd2d09ebee37e29e890f030e9"

[indexing]
contracts = [
  "erc20:0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH fee token
  "erc20:0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK fee token
]
# [sql]
# historical = ["untitled-Moves", "untitled-Moved"]

